service:
 name: nestjs-swagger-serverless-redirect-issue

provider:
 name: aws
 versionFunctions: false
 runtime: nodejs12.x

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-offline

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /
     - http:
         method: any
         path: /{any+}
